// components/header.tsx
import { faBars, faTimes } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Link from "next/link";

interface Props {
    menuIsOpen: boolean;
    onMenuToggle: (isOpen: boolean) => void;
}

function Header(props: Props): JSX.Element  {
    return (
        <header className="flex items-center h-12 px-4 sm:px-6 bg-black-pearl text-white">
            <button
                className="flex items-center lg:hidden mr-4 hover:text-gray-200 transition duration-100"
                onClick={() => props.onMenuToggle(!props.menuIsOpen)}
            >
                {
                    props.menuIsOpen
                        ? <FontAwesomeIcon icon={faTimes} />
                        : <FontAwesomeIcon icon={faBars} />
                }
            </button>
            <Link href="/">
                <a>
                    <h1 className="text-2xl hover:text-gray-200 transition duration-100">NativeDB</h1>
                </a>
            </Link>
        </header>
    );
}

export default Header;

// src/app/header/header.component.ts
import { Subscription } from "rxjs";
import { Component, OnDestroy, OnInit } from "@angular/core";
import { faBars, faTimes } from "@fortawesome/free-solid-svg-icons";

import { MenuService } from "../services/menu.service";

@Component({
    selector: "app-header",
    templateUrl: "./header.component.html",
    styleUrls: ["./header.component.scss"]
})
export class HeaderComponent implements OnInit, OnDestroy {
    public readonly faBars = faBars;
    public readonly faTimes = faTimes;

    public isMenuOpen = false;
    private isMenuOpenSub?: Subscription | null;

    constructor(private readonly menuService: MenuService) {}

    public ngOnInit(): void {
        this.isMenuOpenSub = this.menuService.isOpen$.subscribe(state => {
            this.isMenuOpen = state;
        });
    }

    public ngOnDestroy(): void {
        if (this.isMenuOpenSub) {
            this.isMenuOpenSub.unsubscribe();
            this.isMenuOpenSub = null;
        }
    }

    public toggleMenu(): void {
        this.menuService.toggle();
    }
}

<button
  class="flex items-center lg:hidden mr-4 sm:mr-6 hover:text-gray-200 transition duration-100"
  (click)="toggleMenu()"
>
  <fa-icon
    [icon]="isMenuOpen ? faXmark : faBars"
    [styles]="{ display: 'block' }"
  ></fa-icon>
</button>

<a routerLink="/" class="text-2xl hover:text-gray-200 transition duration-100">
  NativeDB
</a>
